import * as axios from "axios"; // urls com https


export class AuthService {
  static ROLES = {
    'USUARIO': 'SIPAH_USUARIO',
    'USUARIO_EXCLUIR': 'SIPAH_USUARIO_EXCLUIR',
    'CARACTERISTICA': 'SIPAH_CARACTERISTICA',
    'LOG': 'SIPAH_LOG',
    'PACIENTE': 'SIPAH_PACIENTE',
    'PACIENTE_EDITAR_ENTRADA': 'SIPAH_PACIENTE_EDITAR_ENTRADA',
    'PACIENTE_EDITAR_FICHA_SOCIAL': 'SIPAH_PACIENTE_EDITAR_FICHA_SOCIAL',
    'PACIENTE_CAPTURAR_FOTO': 'SIPAH_PACIENTE_CAPTURAR_FOTO',
    'PACIENTE_VISUALIZAR_FOTO': 'SIPAH_PACIENTE_VISUALIZAR_FOTO',
    'PACIENTE_IDENTIFICAR_INTERNADO': 'SIPAH_PACIENTE_IDENTIFICAR_INTERNADO',
    'PACIENTE_REGISTRAR_SAIDA': 'SIPAH_PACIENTE_REGISTRAR_SAIDA',
    'PACIENTE_VISUALIZAR_FICHA_SOCIAL': 'SIPAH_PACIENTE_VISUALIZAR_FICHA_SOCIAL',
    'ATENDIMENTO': 'SIPAH_ATENDIMENTO'
  }
  constructor() { }

  async login(user: string, pass: string) {
    //TODO: implementar requisicao para o SSO
  }

  static async verify(token: string) {
    return {
      "id": "62fce3201bc1df4518e69613",
      'user_name': "André Lucas",
      'cpf':'99999999999',
      "unit_id": "9999999999", // CNPJ
      "unit_name": "HOSPITAL E PRONTO SOCORRO 28 DE AGOSTO",      
      'roles': [
        "SIPAH_USUARIO",
        "SIPAH_PACIENTE",
        "SIPAH_PACIENTE_EDITAR_FICHA_SOCIAL",
        "SIPAH_PACIENTE_VISUALIZAR_FICHA_SOCIAL",
        "SIPAH_PACIENTE_CAPTURAR_FOTO",
        "SIPAH_PACIENTE_VISUALIZAR_FOTO",
        "SIPAH_PACIENTE_IDENTIFICAR_INTERNADO",
        "SIPAH_PACIENTE_REGISTRAR_SAIDA",
        "SIPAH_ATENDIMENTO"]
    };
  }

}
