version: '3.7'
services:

  mongodb:
    image: mongo:5.0.8
    container_name: mongodb_ticados
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e[&W*UcGSVBruETSTW
    networks:
      - ticados

  mongo-express:
    image: mongo-express
    container_name: mongo_express_ticados
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: e[&W*UcGSVBruETSTW
      ME_CONFIG_MONGODB_URL: mongodb://root:e[&W*UcGSVBruETSTW@192.168.224.2:27017
    depends_on:
      - mongodb
    networks:
      - ticados

  backend:
    image: node:16
    container_name: ticados_backend
    restart: always
    working_dir: /app
    command: bash -c 'npm install && npm run run:dev'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=3300
      - MONGODB_DATABASE=ticados_ses
      - MONGODB_USER=root
      - MONGODB_PASSWORD=e[&W*UcGSVBruETSTW
      - MONGODB_HOST=mongodb://192.168.224.2:27017
    ports:
      - "3300:3300"
    networks:
      - ticados

volumes:
  mongo_data:

networks:
  ticados:
    driver: bridge
