version: '3.7'
services:

  ticados-mongodb:
    image: mongo:4.4.6
    container_name: ticados-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - '/etc/timezone:/etc/timezone'
      - '/etc/localtime:/etc/localtime'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e[&W*UcGSVBruETSTW   

  ticados-mongo-express:
    image: mongo-express
    container_name: ticados-mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: e[&W*UcGSVBruETSTW
      ME_CONFIG_MONGODB_URL: mongodb://root:e[&W*UcGSVBruETSTW@10.200.7.27:27018
    depends_on:
      - ticados-mongodb    

  ticados-backend:
    image: node:16
    container_name: ticados-backend
    restart: always
    working_dir: /app
    command: bash -c 'npm install && npm run run:dev'
    volumes:
      #- ./:/app
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - /opt/ticados-backend/images:/app/images
    environment:
      - NODE_ENV=development
      - PORT=3300
      - MONGO_DBNAME=ticados_ses
      - MONGO_USER=root
      - MONGO_PASS=e[&W*UcGSVBruETSTW
      - MONGO_URL=mongodb://10.200.7.27:27018
    ports:
      - "3301:3300"    
    depends_on:
      - ticados-mongodb
volumes:
  mongo_data:

