version: '3.7'
services:

  ticados-mongodb:
    image: mongo:5.0.8
    container_name: ticados-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e[&W*UcGSVBruETSTW   

  ticados-mongo-express:
    image: ticados-mongo-express
    container_name: mongo-express-ticados
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: e[&W*UcGSVBruETSTW
      ME_CONFIG_MONGODB_URL: mongodb://root:e[&W*UcGSVBruETSTW@10.200.7.23:27017
    depends_on:
      - ticados-mongodb    

  ticados-backend:
    image: node:16
    container_name: ticados-backend
    restart: always
    working_dir: /app
    command: bash -c 'npm install && npm run run:prod'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=3300
      - MONGO_DBNAME=ticados_ses
      - MONGO_USER=root
      - MONGO_PASS=e[&W*UcGSVBruETSTW
      - MONGO_URL=mongodb://10.200.7.23:27017
    ports:
      - "3300:3300"    
    depends_on:
      - ticados-mongodb
volumes:
  mongo_data:

